trigger:
  batch: true
  branches:
    include:
    - master

workspace:
  clean: all

pool: Linux

variables:
  DockerVersion: 19.03.6
  DockerRegistry: DockerHub

steps:
- task: DockerInstaller@0
  displayName: Install Docker
  inputs:
    dockerVersion: $(DockerVersion)
    releaseType: stable

- task: Docker@2
  displayName: Login to Container Registry
  inputs:
    command: login
    containerRegistry: $(DockerRegistry)
  
- task: Docker@2
  displayName: Docker Build
  inputs:
    command: build
    Dockerfile: '**/Dockerfile'

- task: Docker@2
  displayName: Push to Registry
  enabled: false
  inputs:
    command: push
    repository: unstoppablemango/docker-kimchi
    tags: latest

- task: Docker@2
  displayName: Logout of Container Registry
  inputs:
    command: logout
    containerRegistry: $(DockerRegistry)
